AlumniWebsite/AlumniWebsite/urls.py
"""
Definition of urls for AlumniWebsite.
"""

from datetime import datetime

from django.conf.urls import url
import django.contrib.auth.views
from django.conf.urls.static import static
from django.conf import settings

import app.forms
import app.views
import app.actions

# Uncomment the next lines to enable the admin:
from django.conf.urls import include
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Primary Pages
    url(r'^$', app.views.home, name='home'),
    url(r'^events/$', app.views.events, name='events'),
    url(r'^alumni/$', app.views.alumni_batches, name='alumni'),
    url(r'^contribute/$', app.views.contribute, name='contribute'),
    url(r'^contact/$', app.views.contact, name='contact'),
    url(r'^school/$', app.views.school, name='school'),
    url(r'^team/$', app.views.team, name='team'),

    # Alumni listings and profiles
    url(r'^alumni/batch/$', app.views.alumni_batches, name='alumni/batches'),
    url(r'^alumni/circles/$', app.views.alumni_circles, name='alumni/circles'),
    url(r'^alumni/distinguished/$', app.views.alumni_distinguished, name='alumni/distinguished'),
    url(r'^alumni/search/$', app.views.alumni_search, name='alumni/search'),
    url(r'^alumni/batch/(?P<batch>[0-9]{4})/$', app.views.alumni_batchlist),
    url(r'^profile/(?P<username>\w*)/?$', app.views.profile, name='profile'),
    url(r'^settings/profile/edit/$', app.views.profile_edit, name='profile/edit'),
    url(r'^actions/befriend/(?P<username>\w*)/?$', app.actions.befriend),
    url(r'^actions/unfriend/(?P<username>\w*)/?$', app.actions.unfriend),
    url(r'^projects/water/$', app.views.water_harvesting, name="projects/water"),

    # Authorization and Administration
    url(r'^login/$',
        django.contrib.auth.views.login,
        {
            'template_name': 'app/login.html',
            'authentication_form': app.forms.BootstrapAuthenticationForm,
            'extra_context':
            {
                'title': 'Log in',
                'year': datetime.now().year,
            }
        },
        name='login'),
    url(r'^logout$',
        django.contrib.auth.views.logout,
        {
            'next_page': '/',
        },
        name='logout'),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AlumniWebsite/app/models.py
"""
Definition of models.
"""

from django.db import models
from django.contrib.auth.models import User


# Models about user and profile data.


class Alumnus(models.Model):
    class Meta:
        verbose_name_plural = "Alumni"

    def __str__(self):
        return self.user.username

    SEX_CHOICES = (
        ('M', 'Male'),
        ('F', 'Female'),
        ## Displayed grouped as LGBTQ / Others
        ('L', 'Lesbian'),
        ('G', 'Gay'),
        ('B', 'Bisexual'),
        ('T', 'Transgender'),
        ('Q', 'Queer'),
    )
    RELATIONSHIP_CHOICES = (
        ('MR', 'Married'),
        ('SN', 'Single'),
        ('RL', 'In a Relationship'),
        ('DV', 'Divorced'),
    )
    VALIDITY_CHOICES = (
        ('V', 'Validated'),
        ('P', 'Paid'),
        ('U', 'Unchecked'),
        ('B', 'Blocked'),
    )

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='profile/', default='profile/_defaultavatar.png')
    birth_date = models.DateField(null=True)
    jobtitle = models.CharField(max_length=50, null=True)
    workplace = models.CharField(max_length=100, null=True)
    batch = models.IntegerField(null=True)
    sex = models.CharField(max_length=1, choices=SEX_CHOICES, null=True)
    admission_number = models.CharField(max_length=20, null=True)
    current_address = models.TextField(max_length=500, null=True)
    permanent_address = models.TextField(max_length=500, null=True)
    phone_mobile = models.CharField(max_length=20, null=True)
    phone_home = models.CharField(max_length=20, null=True)
    phone_work = models.CharField(max_length=20, null=True)
    relationship_status = models.CharField(max_length=2, null=True, choices=RELATIONSHIP_CHOICES)
    validity_code = models.CharField(max_length=1, choices=VALIDITY_CHOICES, default='U')


class Circle(models.Model):
    FRIENDSHIP_CHOICES = (
        ('FR', 'Friends'),
        ('AQ', 'Acquaintances'),
    )

    def __str__(self):
        return self.friend.user.username + ' is a friend of ' + self.user.user.username

    user = models.ForeignKey(Alumnus, related_name='alumnus_user')
    friend = models.ForeignKey(Alumnus, related_name='alumnus_friend')
    type = models.CharField(max_length=2, choices=FRIENDSHIP_CHOICES)
    unique_together = ((user, friend),)


# Models about event and program data


class Event(models.Model):
    def __str__(self):
        return self.name
    name = models.CharField(max_length=50)
    subtitle = models.CharField(max_length=100)
    description = models.TextField(max_length=2500)
    date = models.DateField()

AlumniWebsite/app/templates/app/alumni_batches.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<p>Search our list to find all of St. Thomas' </p>

<hr />

<ul class="nav nav-pills">
    <li class="active" role="presentation"><a href="#">Batch Classification</a></li>
    <li role="presentation"><a href="{% url 'alumni/circles' %}">Your Circles</a></li>
    <li role="presentation"><a href="{% url 'alumni/distinguished' %}">Distinguished Alumni</a></li>
    <li role="presentation"><a href="{% url 'alumni/search' %}">Search Alumni</a></li>
</ul>

<hr />

<div class="row">
    {% for batch in batches %}
        <div class="batch-link col-md-2 col-sm-3 col-xs-6">
            <a href="/alumni/batch/{{batch}}/">
                {{ batch }}
            </a>
        </div>
    {% endfor %}
</div>

{% endblock %}

AlumniWebsite/app/templates/app/alumni_batchlist.html
{% extends "app/layout.html" %}

{% block content %}
{% load staticfiles %}

<h2>
    {{ title }}.
</h2>
<p>Find all students of the {{ batch }} batch here.</p>

<hr />
<div class="people-list">
    {% for person in people %}
        <div class="row people-item">
            <a href="/profile/{{ person.user.username }}">
                <div class="col-sm-1 col-xs-3">
                    <img src="{{ person.picture.url }}" class="img-circle" height="40" width="40"/>
                </div>
                <div class="col-sm-3 col-xs-9 people-data">
                    {{ person.user.first_name }} {{ person.user.last_name }}
                </div>
                <div class="col-sm-4 hidden-xs people-data">
                    Batch of {{ person.batch }}
                </div>
                <div class="col-sm-4 hidden-xs people-data">
                    {{ person.jobtitle }}, {{ person.workplace }}
                </div>
            </a>
        </div>
    {% endfor %}
</div>

{% endblock %}

AlumniWebsite/app/templates/app/alumni_distinguished.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<p>Search our list to find all of St. Thomas' </p>

<hr />

<ul class="nav nav-pills">
    <li role="presentation"><a href="{% url 'alumni/batches' %}">Batch Classification</a></li>
    <li role="presentation"><a href="{% url 'alumni/circles' %}">Your Circles</a></li>
    <li class="active"  role="presentation"><a href="#">Distinguished Alumni</a></li>
    <li role="presentation"><a href="{% url 'alumni/search' %}">Search Alumni</a></li>
</ul>

{% endblock %}

AlumniWebsite/app/templates/app/alumni_search.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<p>Search our list to find all of St. Thomas' </p>

<hr />

<ul class="nav nav-pills">
    <li role="presentation"><a href="{% url 'alumni/batches' %}">Batch Classification</a></li>
    <li role="presentation"><a href="{% url 'alumni/circles' %}">Your Circles</a></li>
    <li role="presentation"><a href="{% url 'alumni/distinguished' %}">Distinguished Alumni</a></li>
    <li class="active" role="presentation"><a href="#">Search Alumni</a></li>
</ul>

<hr />

<section>
    <div class="form-group">
        <form method="get" action="{% url 'alumni/search' %}" class="form-inline" id="search-form">
            <label for="alumniSearch" class="sr-only">Search Query</label>
            <input name="q" id="alumniSearch" class="form-control" type="search" placeholder="Search here ..." />
            <button type="submit" class="btn btn-default">Search</button>
        </form>
    </div>
</section>
<section>
    <div class="people-list">
        {% for person in results %}
            <div class="row people-item">
                <a href="/profile/{{ person.user.username }}">
                    <div class="col-sm-1 col-xs-3">
                        <img src="{{ person.picture.url }}" class="img-circle" height="40" width="40"/>
                    </div>
                    <div class="col-sm-3 col-xs-9 people-data">
                        {{ person.user.first_name }} {{ person.user.last_name }}
                    </div>
                    <div class="col-sm-4 hidden-xs people-data">
                    Batch of {{ person.batch }}
                    </div>
                    <div class="col-sm-4 hidden-xs people-data">
                        {{ person.jobtitle }}, {{ person.workplace }}
                    </div>
                </a>
            </div>
        {% endfor %}
    </div>
</section>
{% endblock %}

AlumniWebsite/app/templates/app/contact.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>

<div class="row">
    <div class="col-md-6">
        <h3>St. Thomas Alumni Association</h3>

        <address>
            St. Thomas School<br />
            Sector-3, Dhurwa<br />
            Ranchi.<br />
            <abbr title="Phone">Ph. No.:</abbr>
            0651.2446649
        </address>

        <address>
            <strong>Email:</strong> <a href="mailto:contactus@stthomasalumni.org">ContactUs@stthomasalumni.org</a><br />
            <strong>Website Complaints:</strong> <a href="mailto:animeshsinha1309@gmail.com">AnimeshSinha1309@gmail.com</a><br />
        </address>
    </div>
</div>

{% endblock %}

AlumniWebsite/app/templates/app/contribute.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}.</h2>
<p>Give back a to your school and to quality education of people in our country.</p>
<hr />

<div class="row">
    <h3 class="col-sm-8">Help better education around you and contribute to a worthy cause.</h3>
    <div class="col-sm-4"><a class="btn btn-success btn-lg"><h4>Make a Donation</h4></a></div>
</div>
<br />
<div class="row">
    <div class="col-sm-12">
        <h3>Other ways you can contribute:</h3>
        <h4 style="padding: 5px 50px;"><a href="#">Volunteer to teach the less privileged.</a></h4>
        <h4 style="padding: 5px 50px;"><a href="#">Share your experiences with our students.</a></h4>
        <h4 style="padding: 5px 50px;"><a href="#">Organize sessions for Special Education.</a></h4>
        <h4 style="padding: 5px 50px;"><a href="#">Help us develop our Laboratories.</a></h4>
    </div>
</div>
<br />
<div class="row">
    <div class="col-sm-12">
        <a href="{% url 'projects/water' %}" class="btn btn-lg btn-primary">
            Participate in the the Water Harvesting Project
        </a>
    </div>
</div>

{% endblock %}

AlumniWebsite/app/templates/app/events.html
{% extends "app/layout.html" %}

{% block content %}
{% load staticfiles %}

<h2>{{ title }}.</h2>
<p>Use this area to provide additional information.</p>

<hr />

<div class="row eventcard-container">
    <div class="event-xmega">
        <h3>{{ main_event.name }}</h3>
        <div class="row">
            <h5 class="col-md-8">{{ main_event.subtitle }}</h5>
            <strong class="col-md-4">{{ main_event.date }}</strong>
        </div>
        <div class="image-set container">
            <div class="row">
                <img src="{% static 'app/images/gallery/demo/event1-1.jpg' %}" alt="Image" />
                <img src="{% static 'app/images/gallery/demo/event1-2.jpg' %}" alt="Image" />
                <img src="{% static 'app/images/gallery/demo/event1-3.jpg' %}" alt="Image" />
            </div>
        </div>
        <div>
            {{ main_event.description }}
        </div>
    </div>
</div>
<div class="row">
    {% for event in future_events %}
        <div class="col-md-4 eventcard-container"> 
           <div class="event-xmega">
                <h3>{{ event.name }}</h3>
                <div class="row">
                    <h5 class="col-md-6">{{ event.subtitle }}</h5>
                    <strong class="col-md-6">{{ event.date }}</strong>
                </div>
                <div>
                    {{ event.description }}
                </div>
            </div>
        </div>
    {% endfor %}
</div>

<div class="row">
    {% for event in past_events %}
        <div class="col-md-4 eventcard-container"> 
           <div class="event-xmega">
                <h3>{{ event.name }}</h3>
                <div class="row">
                    <h5 class="col-md-6">{{ event.subtitle }}</h5>
                    <strong class="col-md-6">{{ event.date }}</strong>
                </div>
                <div>
                    {{ event.description }}
                </div>
            </div>
        </div>
    {% endfor %}
</div>

{% endblock %}

AlumniWebsite/app/templates/app/index.html
{% extends "app/layout.html" %}

{% block content %}
{% load staticfiles %}
<div class="jumbotron">
    <div class="row">
        <div class="col-sm-3">
            <img src="{% static 'app/images/logo.svg' %}" class="img-circle" height="250" width="250">
        </div>
        <div class="col-sm-9">
            <h1>St. Thomas Alumni</h1>
            <p class="lead">St. Thomas Alumni Association, Ranchi (STAAR) is a privately organized alumni association
            working together with the school to keep all Friends in close and development friendly networks.</p>
            <p><a href="http://www.stthomasschoolranchi.com/" class="btn btn-primary btn-large" target="_blank">St. Thomas School &raquo;</a></p>
        </div>
    </div>
</div>

<div class="row" style="background-color: #333333;">
    <div id="carousel-home" class="carousel slide col-md-8 col-md-offset-2" data-ride="carousel">
        <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#carousel-home" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-home" data-slide-to="1"></li>
            <li data-target="#carousel-home" data-slide-to="2"></li>
        </ol>

        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img width="1000" height="500" src="{% static 'app/images/gallery/demo/demohome1.jpg' %}" alt="...">
                <div class="carousel-caption">
                </div>
            </div>
            <div class="item">
                <img width="1000" height="500" src="{% static 'app/images/gallery/demo/demohome2.jpg' %}" alt="...">
                <div class="carousel-caption">
                </div>
            </div>
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-home" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-home" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>What we Do</h2>
        <p>
            Once a St. Thomasian, always a St. Thomasian. Its a relationship for life, and strive to
            make those bonds stronger and bring together all students and staff to develop an atmosphere
            or academic creativity and belongingness to the community. Let's relive the nostalgia and 
            celebrate the St. Thomas fraternity!
        </p>
        <p><a class="btn btn-default" href="{% url 'contact' %}" target="_blank">Join in &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Hall of Fame</h2>
        <p>
            We take pride in each of our alumni, and all of them make an impact on the world: Our Alumni
            flourish in varied sectors from television, sports, service sectors to government and 
            research.
        </p>
        <p><a class="btn btn-default" href="{% url 'alumni/distinguished' %}" target="_blank">View General Achievements &raquo;</a></p>
        <p><a class="btn btn-default" href="{% url 'alumni/distinguished' %}" target="_blank">View Achievements in Science &raquo;</a></p>
        <p><a class="btn btn-default" href="{% url 'alumni/distinguished' %}" target="_blank">View Achievements in Commerce &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Our Plans</h2>
        <p>
            Join us in bettering our world, help out the school in its varied education programs that
            include pushing the bounds in top-end education and inspiring innovation to uplifting every
            bit of the society and helping them learn. Take part in the campaign - Contribute to your
            society.
        </p>
        <p><a class="btn btn-default" href="{% url 'contribute' %}" target="_blank">Partake in our Activities &raquo;</a></p>
    </div>
</div>

{% endblock %}

AlumniWebsite/app/templates/app/layout.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ title }}</title>
    {% load staticfiles %}
    <link rel="icon" href="{% static 'app/images/favicon.ico' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/paperswatch.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static 'app/content/site.css' %}" />
    <script src="{% static 'app/scripts/modernizr-2.6.2.js' %}"></script>
</head>

<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="/" class="navbar-brand">St. Thomas Alumni</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'events' %}">Events</a></li>
                    <li><a href="{% url 'alumni' %}">Alumni</a></li>
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" role="button" 
                               aria-haspopup="true" aria-expanded="false">
                            More <span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="{% url 'team' %}">Team</a></li>
                            <li><a href="{% url 'school' %}">School</a></li>
                            <li><a href="{% url 'contribute' %}">Contribute</a></li>
                            <li><a href="{% url 'contact' %}">Contact</a></li>
                        </ul>
                    </li>
                </ul>
                {% include 'app/loginpartial.html' %}
            </div>
        </div>
    </div>

    <div class="container body-content">
{% block content %}{% endblock %}
        <hr/>
        <footer>
            <p>
                &copy; {{ year }} - Animesh Sinha
                <a href="http://www.github.com/AnimeshSinha1309/AlumniWebsite">(GitHub)</a>
            </p>
        </footer>
    </div>

    <script src="{% static 'app/scripts/jquery-1.10.2.js' %}"></script>
    <script src="{% static 'app/scripts/bootstrap.js' %}"></script>
    <script src="{% static 'app/scripts/respond.js' %}"></script>
{% block scripts %}{% endblock %}

</body>
</html>

AlumniWebsite/app/templates/app/login.html
{% extends "app/layout.html" %}

{% block content %}

<h2>{{ title }}</h2>
<div class="row">
    <div class="col-md-8">
        <section id="loginForm">
            <form action="." method="post" class="form-horizontal">
                {% csrf_token %}
                <h4>Use a local account to log in.</h4>
                <hr />
                <div class="form-group">
                    <label for="id_username" class="col-md-2 control-label">User name</label>
                    <div class="col-md-10">
                        {{ form.username }}
                    </div>
                </div>
                <div class="form-group">
                    <label for="id_password" class="col-md-2 control-label">Password</label>
                    <div class="col-md-10">
                        {{ form.password }}
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="hidden" name="next" value="/" />
                        <input type="submit" value="Log in" class="btn btn-default" />
                    </div>
                </div>
                {% if form.errors %}
                <p class="validation-summary-errors">Please enter a correct user name and password.</p>
                {% endif %}
            </form>
        </section>
    </div>
    <div class="col-md-4">
        <section id="socialLoginForm"></section>
    </div>
</div>

{% endblock %}


{% block scripts %}

    {% load staticfiles %}
<script src="{% static 'app/scripts/jquery.validate.min.js' %}"></script>

{% endblock %}

AlumniWebsite/app/templates/app/loginpartial.html
{% if user.is_authenticated %}
<form id="logoutForm" action="/logout" method="post" class="navbar-right">
    {% csrf_token %}
    <ul class="nav navbar-nav navbar-right">
        <li><a href="/profile/" class="navbar-brand">{{ user.first_name }} {{ user.last_name }}</a></li>
        <li><a href="javascript:document.getElementById('logoutForm').submit()">Log off</a></li>
    </ul>

</form>

{% else %}

<ul class="nav navbar-nav navbar-right">
    <li><a href="{% url 'login' %}">Log in</a></li>
</ul>

{% endif %}

AlumniWebsite/app/templates/app/profile.html
{% extends "app/layout.html" %}

{% block content %}
{% load staticfiles %}

<div>
    <div class="row">
        <div class="col-md-4 text-center">
            <img src="{{ data.picture.url }}" height="200" width="200" class="img-circle" />
            <h2>{{ data.user.first_name }} {{ data.user.last_name }}</h2>
            {% if status == 'Unconnected' %}
                <a href="/actions/befriend/{{ data.user.username }}" class="btn btn-primary">
                    Add to Friends List
                </a>
            {% elif status == 'Friends' %}
                <a href="/actions/unfriend/{{ data.user.username }}" class="btn btn-primary">
                    Remove from Friends List
                </a>
            {% elif status == 'Self' %}
                <a href="{% url 'profile/edit' %}" class="btn btn-primary">
                    Edit your Profile
                </a>
            {% endif %}
        </div>
        <div class="col-md-8">
            {% if data.user.email %}
                <div class="profile-item">
                    <strong>Email Address: </strong>{{ data.user.email }}
                </div>
            {% endif %}
            {% if data.jobtitle and data.workplace %}
                <div class="profile-item">
                    <strong>Works as: </strong>{{ data.jobtitle }}, {{ data.workplace }}
                </div>
            {% endif %}
            {% if data.batch %}
                <div class="profile-item">
                    {% if data.birth_date %}<strong>Born on: </strong>{{ data.birth_date }}.{% endif %}
                    <strong> Batch of </strong>{{ data.batch}}
                </div>
            {% endif %}
            {% if data.phone_mobile %}
                <div class="profile-item">
                    <strong>Phone No. (Mobile): </strong>{{ data.phone_mobile }}
                </div>
            {% endif %}
            {% if data.phone_work %}
                <div class="profile-item">
                    <strong>Phone No. (Work): </strong>{{ data.phone_work }}
                </div>
            {% endif %}
            {% if data.relationship_status %}
                <div class="profile-item">
                    <strong>Relationship Status: </strong>{{ data.get_relationship_status_display }}
                    (<strong>Gender: </strong>{{ data.get_sex_display }})
                </div>
            {% endif %}
        </div>
    </div>

    <div class="container" style="margin-top: 50px;">
        <button class="btn btn-success" type="button" data-toggle="collapse" 
                data-target="#friends" aria-expanded="false" aria-controls="friends">
            Friend List
        </button>
        <div class="row collapse" id="friends">
            {% for friend in friends %}
                <a class="col-md-2 col-sm-3 col-xs-6 text-center" style="padding: 10px 0;"
                        href="/profile/{{ friend.friend.user.username }}">
                    <img src="{{ friend.friend.picture.url }}" class="img-circle" height="100" width="100"
                            title="{{ friend.friend.user.first_name }} {{ friend.friend.user.last_name }}" 
                            data-toggle="tooltip" data-placement="top" />
                </a>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

{% block scripts %}
<script> $(function () { $('[data-toggle="tooltip"]').tooltip() }) </script>
{% endblock %}

AlumniWebsite/app/templates/app/profile_edit.html
{% extends "app/layout.html" %}

{% block content %}
{% load staticfiles %}

<h2>{{ title }}.</h2>
<p>Update and Add your profile data here.</p>

<form method="post" action="{% url 'profile/edit' %}" class="form-horizontal container">
    {% csrf_token %}
    {% for field in form %}
        <div class="form-group">
            <div class="field-validation-error">{{ field.errors }}</div>
            <label for="{{field.id_for_label}}" class="col-md-2 control-label">{{ field.label }}</label> 
            <div class="col-md-10"> {{ field }} </div>
            {% if field.help_text %} <p class="help">{{ field.help_text|safe }}</p> {% endif %}
        </div>
    {% endfor %}
    <div class="col-md-10 col-md-offset-2">
        <input type="submit" value="Confirm the Edit" class="btn btn-primary" style="margin-top:15px" />
    </div>
</form>

{% endblock %}

AlumniWebsite/app/templates/app/team.html
{% extends "app/layout.html" %}

{% block content %}
{% load staticfiles %}

<h2>{{ title }}.</h2>
<p>People that make the Alumni Association happen</p>

<hr />

<div class="container">
    <div class="row team-committee">
        <h3>Alumni Association Committee Members</h3>
        <div class="col-sm-4">
            <img src="{% static 'app/images/committee/manish khatore.jpg' %}" class="img-circle img-halo"
                    height="200" width="200" />
            <h4>Manish Khatore</h4>
            <p class="font-large">President</p>
        </div>
        <div class="col-sm-4">
            <img src="{% static 'app/images/committee/vineet kumar.jpg' %}" class="img-circle img-halo"
                    height="200" width="200" />
            <h4>Vineet Kumar</h4>
            <p class="font-large">Vice-President</p>
        </div>
        <div class="col-sm-4">
            <img src="{% static 'app/images/committee/mohua rai.jpg' %}" class="img-circle img-halo"
                    height="200" width="200" />
            <h4>Mohua Rai</h4>
            <p class="font-large">Honorary General Secretary</p>
        </div>
        <div class="col-sm-4">
            <img src="{% static 'app/images/committee/avinash kumar.jpg' %}" class="img-circle img-halo"
                    height="200" width="200" />
            <h4>Avinash Kumar Singh</h4>
            <p class="font-large">Joint Secretary</p>
        </div>
        <div class="col-sm-4">
            <img src="{% static 'app/images/committee/anirban roy.jpg' %}" class="img-circle img-halo"
                    height="200" width="200" />
            <h4>Anirban Roy</h4>
            <p class="font-large">Treasurer</p>
        </div>
        <div class="col-sm-4">
            <img src="{% static 'app/images/committee/arundhati chakrabarty.jpg' %}" class="img-circle img-halo"
                    height="200" width="200" />
            <h4>Arundhati Chakrabarty</h4>
            <p class="font-large">Association Member</p>
        </div>
    </div>
    <div class="row team-developers">
        <h3>Development and Task force</h3>
        <div class="col-sm-4 col-sm-offset-4">
            <img src="{% static 'app/images/committee/animesh sinha.jpg' %}" class="img-circle img-halo"
                    height="150" width="150" />
            <h4>Animesh Sinha</h4>
            <p class="font-large">Developer</p>
        </div>
    </div>
    
</div>

{% endblock %}